name: Release
on:
  push:
    branches:
      - 'master'
jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: autotag
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.autotag.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.autotag.outputs.tag }}
          release_name: ${{ steps.autotag.outputs.tag }}
          body: ${{ steps.autotag.outputs.clean_changelog }}
